### ISSUE TITLE
Design error with search screen in member list

### ISSUE THREAD

**Issue by YannickB** [xpansa/community-web#1]
see screenshot, on firefox with 17" screen 1920x1080
![yourcompany_-_mamber_list_-_2014-10-31_15 06 52](https://cloud.githubusercontent.com/assets/225578/4861859/2f8a3202-6107-11e4-89ac-26ddef8d8de1.png)

**Comment by okuryan** [comment]
Yannick, that is fixed and should be pushed in repo. Please, check

**Comment by YannickB** [comment]
Indead the design error is corrected, thank you

This allowed me to test the search, it seems when I try to type 'admin' or 'mark' in the who searchbox nothing no member are returned.

**Comment by okuryan** [comment]
Yannick, name of the member is searched in the main Search field. 
Who? field per Juliens comment is searching by the following algorithm:
"Who? = Group name (will search users who belong to particular group)"

**Comment by YannickB** [comment]
Oh ok I see, ok no more problem in this case. I let the ticket open because I'll rename Who? into Group, consider it done.
