### ISSUE TITLE
Hide some icon on the topbor

### ISSUE THREAD

**Issue by YannickB** [xpansa/community-web#11]
For now hide the money icon and the letter icon on the topbar since they're not working

**Comment by okuryan** [comment]
Looking at it

**Comment by nedaszilinskas** [comment]
Hello Yannick,

We have hidden those icons by adding a class ".hidden" to li elements.

Nedas

**Comment by YannickB** [comment]
Hello Nedas, it's been a long time since we've talked glad to see you :)

I confirm everything is all right, I'll close the ticket. Think about letting a 'fix #issue_number' in the commit name next time, it'll link the commit to the issue directly :)
