### ISSUE TITLE
Member list

### ISSUE THREAD

**Issue by YannickB** [xpansa/community-web#12]
Like in backoffice, display only the partner linked to a user.

Here is the domain I use : [('user_ids','!=',False)]

**Comment by djulien19** [comment]
and the group? All the members belonging to a group will be displayed also by completing this field.

**Comment by YannickB** [comment]
Yes but it's still only member which are displayed, they are only search by group the domain is ok.

**Comment by okuryan** [comment]
will look at it

**Comment by YannickB** [comment]
Done
