### ISSUE TITLE
Size of text field in proposition

### ISSUE THREAD

**Issue by YannickB** [xpansa/community-web#16]
Feedback shall be directly under indic/rate and same width.

description shall take all the space until indic/rate
![dev_-_view_announcement_-_2014-11-04_16 32 01](https://cloud.githubusercontent.com/assets/225578/4902244/f6583c48-6437-11e4-8695-07e84db0d0f1.png)

**Comment by okuryan** [comment]
WIll look into this if not take too much time

**Comment by okuryan** [comment]
Yannick, please, take a look at it. That should also be resolved

**Comment by YannickB** [comment]
Looking at it on http://176.31.200.227, I see no change and no commit on github, where shall I look?

**Comment by okuryan** [comment]
Hi Yannick, github commit is here https://github.com/xpansa/community-web/commit/a5bee2018a4496c74dd005255a9feaf7f98770f5

**Comment by YannickB** [comment]
Ok for me
