### ISSUE TITLE
Vote

### ISSUE THREAD

**Issue by YannickB** [xpansa/community-web#18]
In proposition, hide indic/rate and feedback when already_accepted is false

The list of indic/rate shall be got from the category, the user shall directly have the list and shall not be able to modify it (remove the + button), he shall just be able to change the rate value.
To get the list of indic, see https://github.com/YannickB/community-management/blob/master/__unreviewed__/vote/vote.py line 244

**Comment by okuryan** [comment]
Looking at it

**Comment by veryberry** [comment]
Fixed in commits https://github.com/xpansa/community-web/commit/f4557870586ab32d1944e258d6250c3c93ee2f11 , 
https://github.com/xpansa/community-web/commit/f0397428918f27ff20a604e0a289c06703090ab9

**Comment by YannickB** [comment]
Ok the votes are correctly loaded when I create a new reply, but I still can make the whole workflow work. Especially I have a question, how can you modify an existing proposition?

Here is my test workflow : 
-Click on make a reply
-Fill the proposition and submit (at this point, indic/feedback fields must be hidden, base your domain on invisible -> already_accepted = False)
-Navigate through workflow. We must be able to modify the fields at any times.
-When you are at waiting_vote state, stay log as replier and fill the indic/feedback field. Did you understood that indic/feedback fields correspond to the vote.vote of the current user? Depending of the user you are log in, the value of theses fields are not the same.
-Then log as the announcer, go to the proposition and fill his own indic/feedback fields to create his vote.vote. If the both vote.vote for the replier and the announcer are correctly filled, both vote.vote will automatically have is_complete = True and the proposition will automatically go to the paid state.

Also I have a strange bug, when I click on make a reply it load the last proposition of my current user instead of creating a new one.

**Comment by veryberry** [comment]
1 Could you please describe where should be displayed votes from both announcer and proposer on the same page, for now design allows to display vote from one person per reply
2 >> Also I have a strange bug, when I click on make a reply it load the last proposition of my current user instead of creating a new one.
it can be in case when user has already posted reply on this announcement and now it's available to edit until already_accepted = True. Mb it is also an answer to your question  "Especially I have a question, how can you modify an existing proposition?"

**Comment by veryberry** [comment]
1. Added possibility to add more than 1 proposition (only if user does not have draft/open propositions for the announcement).
2. Added possibility to update proposition until it's accepted. After it only feedback field is available for edition.
3. Commented vote functionality.
   Commit https://github.com/xpansa/community-web/commit/6f31ecd4d56956cedff3569d9bb339b68f122eb6

**Comment by YannickB** [comment]
Ok tested and approved. I think with this everything is done. Thank you for your hard work.
