### ISSUE TITLE
Javascript error after module splitting

### ISSUE THREAD

**Issue by YannickB** [xpansa/community-web#27]
Hello,

After splitting the module (see my repo) I am not able to load anymore the javascript. Look at http://dev-ocm.yolo-consulting.net/marketplace/announcement_detail/i-m-offering-services-about-odoo-customization-1# , make a reply isn't working anymore.

Thanks for the help, I was able to correct most of the error after the split but javascript is my weakness. Also I'd like to have your opinion about how I chose to split the modules.

**Comment by okuryan** [comment]
Yannick, just to make sure I fully understand everything. I see that in your repository https://github.com/YannickB/community-management the last commit was 13 days ago. Also there is only one master branch, so I just try to understand are you referring to splitting community-web modules or to your modules splitting?

**Comment by YannickB** [comment]
Yes this is the wrong branch, the good one if a fork of yours https://github.com/YannickB/community-web

Moreover for the backoffice, since the OCA repo was created you shall look at https://github.com/OCA/vertical-community or https://github.com/YannickB/vertical-community. I'm refering to community-web splitting

**Comment by nedaszilinskas** [comment]
Hello Yannick,

The error states that the javascript openerp.website.theme.views object is not defined.

Please try to add the following lines before including .js files:

<script>
openerp.website.theme = {}
openerp.website.theme.views = {}
</script>

Nedas

**Comment by nedaszilinskas** [comment]
Sorry, ignored script tag in previous comment.

The lines (put it in SCRIPT tag just above .js file includes):
openerp.website.theme = {}
openerp.website.theme.views = {}
Nedas

**Comment by YannickB** [comment]
Hello Nedas, I just made a commit but it doesn't seems to resolve the problem.

Can you please make a merge proposal after testing on your platform?

**Comment by YannickB** [comment]
Ok my bad, I just forgot to make a module update, the javascript works now.

I have still the error with the make a reply button through. It doesn't looks like it has the event on it.

**Comment by YannickB** [comment]
And I finally understood the problem, the openerp.website was also reset in the template module. Check my last commit but it seems it correctly work now. Thanks for your help!
