### ISSUE TITLE
Skills and interest field in member page

### ISSUE THREAD

**Issue by YannickB** [xpansa/community-web#4]
I don't understand how you coded theses fields.

On res.partner, it's too many2many fields, we shall be able to select existing values (defined by the moderators) not having a char field with free values

**Comment by okuryan** [comment]
Yannick,

Actually that is how it was requested by Julien. That field allows not only to select existent skill or interest, but to create a new.

**Comment by YannickB** [comment]
Ok I saw with Julien. I didn't see that it was a kind of many2one, I though it was a simple char field...

I disagree with him on some part on this fields, and we found a compromise : is it possible to modify it so the create part is only possible if the user has the access group account_wallet.group_account_wallet_moderator?

**Comment by veryberry** [comment]
Fixed in commit https://github.com/xpansa/community-web/commit/7369e496824c5e687e7202c0dcc89f34f008bfba

**Comment by YannickB** [comment]
looks ok
